/* HYPRE_config.h.  Generated by configure.  */
/* config/HYPRE_config.h.in.  Generated from configure.in by autoheader.  */

/* Define to dummy `main' function (if any) required to link to the Fortran
   libraries. */
/* #undef F77_DUMMY_MAIN */

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
#define F77_FUNC(name,NAME) name ## _

/* As F77_FUNC, but for C identifiers containing underscores. */
#define F77_FUNC_(name,NAME) name ## _

/* Define if F77 and FC dummy `main' functions are identical. */
/* #undef FC_DUMMY_MAIN_EQ_F77 */

/* BLAS library is system or user provided. */
/* #undef HAVE_BLAS */

/* Define to 1 if you have the `bzero' function. */
#define HAVE_BZERO 1

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `floor' function. */
#define HAVE_FLOOR 1

/* Define to 1 if you have the `gethrtime' function. */
/* #undef HAVE_GETHRTIME */

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* LAPACK library is system or user provided. */
/* #undef HAVE_LAPACK */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <malloc.h> header file. */
/* #undef HAVE_MALLOC_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `pow' function. */
#define HAVE_POW 1

/* Define to 1 if the system has the type `ptrdiff_t'. */
#define HAVE_PTRDIFF_T 1

/* Define to 1 if you have the `sqrt' function. */
#define HAVE_SQRT 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcspn' function. */
#define HAVE_STRCSPN 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strspn' function. */
#define HAVE_STRSPN 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if the routine MPI_Comm_f2c is found. */
/* #undef HYPRE_HAVE_MPI_COMM_F2C */

/* Define to 1 for Solaris. */
/* #undef HYPRE_SOLARIS */

/* Define to 1 for Linux on platforms running any version of CHAOS. */
/* #undef HYPRE_LINUX_CHAOS */

/* Define to 1 for Linux platforms. */
/* #undef HYPRE_LINUX */

/* Define to 1 for Alpha platforms. */
/* #undef HYPRE_ALPHA */

/* Define to 1 for RS6000 platforms. */
/* #undef HYPRE_RS6000 */

/* Define to 1 for IRIX64 platforms. */
/* #undef HYPRE_IRIX64 */

/* Disable MPI, enable serial codes */
/* #undef HYPRE_SEQUENTIAL */

/* HYPRE timing routines are being used */
/* #undef HYPRE_TIMING */

/* Using dxml for Blas */
/* #undef HYPRE_USING_DXML */

/* Using essl for Blas */
/* #undef HYPRE_USING_ESSL */

/* Using internal Hypre routines. */
#define HYPRE_USING_HYPRE_BLAS 1

/* Using internal Hypre routines. */
#define HYPRE_USING_HYPRE_LAPACK 1

/* No global partitioning being used */
/* #undef HYPRE_NO_GLOBAL_PARTITION */

/* Enable OpenMP support */
/* #undef HYPRE_USING_OPENMP */

/* Define to the address where bug reports for this package should be sent. */
#define HYPRE_PACKAGE_BUGREPORT "http://www-casc.llnl.gov/bugs/enter_bug.cgi?product=HYPRE"

/* Date of release */
#define HYPRE_PACKAGE_DATE "2005/12/29"

/* Date and time of release */
#define HYPRE_PACKAGE_DATETIME "2005/12/29 09:25:00"

/* Define to the full name of this package. */
#define HYPRE_PACKAGE_NAME "hypre"

/* Define to the full name and version of this package. */
#define HYPRE_PACKAGE_STRING "hypre"

/* Define to the one symbol short name of this package. */
#define HYPRE_PACKAGE_TARNAME "hypre"

/* Time of release */
#define HYPRE_PACKAGE_TIME "09:25:00"

/* Define to the version of this package. */
#define HYPRE_PACKAGE_VERSION "1.10.0b"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to empty if the keyword `volatile' does not work. Warning: valid
   code using `volatile' can become incorrect without. Disable with care. */
/* #undef volatile */
