#BHEADER***********************************************************************
# (c) 1998   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.14 $
#EHEADER***********************************************************************

###############################################################################
##  All configurable variables are defined in the file named Makefile.config.in
##  When Autoconf is run, it will create a file named Makefile.config which
##  will have all of the configurable variables replaced with their values.
###############################################################################



SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /Users/dalber/research/code/hypre-1.10.0b/src/hypre
exec_prefix = ${prefix}



HYPRE_SRC_TOP_DIR = /Users/dalber/research/code/hypre-1.10.0b/src
HYPRE_BUILD_DIR = /Users/dalber/research/code/hypre-1.10.0b/src/hypre

HYPRE_RELEASE_VERSION = 1.10.0b
HYPRE_RELEASE_DATE = 2005/12/29
HYPRE_RELEASE_TIME = 09:25:00
HYPRE_RELEASE_DATETIME = 2005/12/29 09:25:00

HYPRE_INSTALL_DIR = NONE
HYPRE_LIB_INSTALL = ${exec_prefix}/lib
HYPRE_INC_INSTALL = ${prefix}/include


.SUFFIXES:
.SUFFIXES: .o .f .c .C .cxx

.f.o:
	$(F77) $(FFLAGS) -c $< 
.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< 
.C.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $<
.cxx.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $<


F77       = gfortran
FFLAGS    = -O  $(F77_COMPILE_FLAGS)

CC        = mpicc
CFLAGS    = -O2 $(C_COMPILE_FLAGS)

CXX       = mpicxx
CXXFLAGS  = -O2 $(CXX_COMPILE_FLAGS)

CPPFLAGS  = -DHAVE_CONFIG_H

LINK_CC   = mpicc
LINK_CXX  = mpicxx

AR	  = ar -rcu
RANLIB    = ranlib

LDFLAGS   = -L/usr/lib/gcc-lib/i386-redhat-linux/3.2.3 -L/usr/lib -L/usr/local/lib -L/usr/apps/lib -L/lib 
LDLIBS    = 
LDLIBDIRS = 

INCLUDES = 
LIBDIRS = 
LIBS =    -lm
FLIBS =  -L/sw/lib/gcc4.2/lib/gcc/i686-apple-darwin8/4.2.0 -L/sw/lib/gcc4.2/lib/gcc/i686-apple-darwin8/4.2.0/../../.. -lgfortranbegin -lgfortran -lgcc_s.10.4 -lSystem

##################################################################
##  BABEL Directories
##################################################################
HYPRE_BABEL_DIRS = 

##################################################################
##  LAPACK Library Flags 
##################################################################
HYPRE_LAPACK_SRC_DIR = /Users/dalber/research/code/hypre-1.10.0b/src/lapack
LAPACKLIBS = -lHYPRE_utilities
LAPACKLIBDIRS = -L/Users/dalber/research/code/hypre-1.10.0b/src/hypre/lib

##################################################################
##  BLAS Library Flags 
##################################################################
HYPRE_BLAS_SRC_DIR = /Users/dalber/research/code/hypre-1.10.0b/src/blas
BLASLIBS = -lHYPRE_utilities
BLASLIBDIRS = -L/Users/dalber/research/code/hypre-1.10.0b/src/hypre/lib

##################################################################
##  MPI options
##################################################################
MPIINCLUDE = 
MPILIBDIRS = 
MPILIBS =  
MPIFLAGS = 

##################################################################
##  FEI options
##################################################################
FEIINCLUDE = 
FEILIBS = 
FEILIBDIRS = 
